# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: MicroBumpLayout.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15MicroBumpLayout.proto\"\xd4\x01\n\nMicroBumps\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0b\n\x03row\x18\x02 \x01(\x05\x12\x0b\n\x03\x63ol\x18\x03 \x01(\x05\x12\x0e\n\x01x\x18\x04 \x01(\x02H\x00\x88\x01\x01\x12\x0e\n\x01y\x18\x05 \x01(\x02H\x01\x88\x01\x01\x12\x11\n\x04size\x18\x06 \x01(\x02H\x02\x88\x01\x01\x12\x13\n\x06\x62undle\x18\x07 \x01(\rH\x03\x88\x01\x01\x12\x12\n\x05\x63olor\x18\x08 \x01(\rH\x04\x88\x01\x01\x12\x18\n\x04type\x18\t \x01(\x0e\x32\n.BumpTypesB\x04\n\x02_xB\x04\n\x02_yB\x07\n\x05_sizeB\t\n\x07_bundleB\x08\n\x06_color\"I\n\x0fMicroBumpArrays\x12\x16\n\x0eMicroBumpCount\x18\x01 \x01(\x05\x12\x1e\n\tMicroBump\x18\x02 \x03(\x0b\x32\x0b.MicroBumps*6\n\tBumpTypes\x12\x07\n\x03VSS\x10\x00\x12\x07\n\x03VDD\x10\x01\x12\x0c\n\x08\x46unction\x10\x02\x12\t\n\x05Spare\x10\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'MicroBumpLayout_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_BUMPTYPES']._serialized_start=315
  _globals['_BUMPTYPES']._serialized_end=369
  _globals['_MICROBUMPS']._serialized_start=26
  _globals['_MICROBUMPS']._serialized_end=238
  _globals['_MICROBUMPARRAYS']._serialized_start=240
  _globals['_MICROBUMPARRAYS']._serialized_end=313
# @@protoc_insertion_point(module_scope)
